RSSの1件登録・表示
takeyuwebinc/sample-feedreader-rails pull request #10
Opened 2018-03-09 06:54 UTC by shiraryu

refs #3 

・任意のRSSフィードを登録できるように、new / create　の追加

xml変換部付近で思うように値を取得する考えが及ばず、強引な形になってしまっています。
あと、スクールで「モデルは必要」というように植えつけられてきたので、
コントローラに記述できると思いつつも１行しかないのですが、据え置いてます。
この「モデルが必要」という点も、どういった時は必要/不必要の判断があやふやです。

すいませんが一旦ご確認いただき、レビューの方よろしくお願いいたします。

2018-03-09 07:20 UTC, takeyuweb requested changes

2018-03-09 07:20 UTC, takeyuweb commented on app/controllers/feeds_controller.rb
> +    url = Feed.find(1).url
１件を取り出すには `Feed.first` を使います。
https://railsguides.jp/active_record_querying.html#first

2018-03-09 07:20 UTC, takeyuweb commented on app/models/feed.rb
> +Feed = Class.new(ApplicationRecord)
[この話](https://github.com/takeyuwebinc/takeyuweb-rails/pull/39/files/ddeb43cc4c8192c91aeea62c8ff666cce60ee182..7eceb9537c8b26d7276c4bf2af3a136b925d0a7d#diff-f29c7640ea963c37993f0191494b028d) を読んで、その影響でしょうか。あれは少々特殊な話なので忘れていいです。

ここではふつうに

```ruby
class Feed < ApplicationRecord
  # 省略
```

でつくりましょう。
urlは必須入力なのでバリデーション＆エラー表示もほしいですね。

2018-03-09 07:20 UTC, takeyuweb commented on config/routes.rb
> +  resources :feeds, only:[:index, :new, :create]
細かいところですが
`resources :feeds, only: [:index, :new, :create]` のように、ハッシュリテラルの `:` 後ろにスペースを入れる書き方が読みやすく一般的です。

2018-03-09 07:20 UTC, takeyuweb commented on db/migrate/20180309033241_create_feeds.rb
> +      t.string :url
`Feed`の`url`が存在しないことはありえないので、 `t.string :url, null: false, default: ''` として、空の値（NULL）を許容しないようにしておきましょう。
まだNULLの概念はよくわからないかもしれませんが、特別な理由がない限り `null: false` を指定してやると覚えておくと後で困らないです。

さらに`comment:`を使って説明を書いておけばベストです。

`t.string :url, null: false, default: '', comment: 'RSSフィードのURL'`

これらのことはコードを保守しやすくするための積み重ねです。

2018-03-09 07:20 UTC, takeyuweb commented on db/migrate/20180309033241_create_feeds.rb
> +      t.string :url
マイグレーション（ ` db/migrate/*.rb` のファイル）の変更の前には
`rails db:rollback`
してこのマイグレーションの内容を差し戻しておき、変更後 `rails db:migrate` しなおすようにしましょう。
 `rails db:migrate` の際は、データベース定義と同時に `db/schema.rb` が更新されます。

2018-03-09 07:20 UTC, takeyuweb commented on app/models/feed.rb
> +Feed = Class.new(ApplicationRecord)
RSSフィードのURLから内容を取得するのは、Feedの責務になりますので

```ruby
class Feed < ApplicationRecord
  # 省略

  # RSSから記事リストを取得して返す
  def items
    # url の RSS を取得して記事データの配列を返すコード
  end
end
```

となるのかなと思います。

2018-03-09 07:34 UTC, shiraryu commented
@takeyuweb ご確認ありがとうございます。１つずつ確認しつつ修正していきます。
またわからない際は、ご質問させていただきます！

2018-03-09 07:44 UTC, takeyuweb commented
先のトレーニングFeedを消してもらったのはかんたんのため、というのもあったのですが、

> あと、スクールで「モデルは必要」というように植えつけられてきたので、

正しいです。
が、なんでもかんでも Railsのモデル（ActiveRecord） を無理に使う必要はない、ということです。

Railsのモデル（ActiveRecord）だけがモデルではないというというのを頭のすみに置いておいて貰えればと。
このあたりの記事はだいぶ噛み砕いてモデルについて書いてあるのでわかりやすいかも→ http://at-grandpa.hatenablog.jp/entry/2013/11/01/072636

先のトレーニングの内容だと、『URLにアクセスしてデータをダウンロードする』『ダウンロードしたデータを解析して扱いやすいかたち（オブジェクト）にする』というロジックが必要だったのですが、これはすべて `RSS::Parser.parse` の中に閉じ込めてあるため、これをそのまま使えばよく、他にモデルは不要でした。

2018-03-09 07:55 UTC, shiraryu commented
@takeyuweb 
ありがとうございます！
前回の件、ようやく理解できました。
なんとなくイケた感があるまま進んでいたので反省です（汗）
（結局どこかで詰まるのに、、、）
これまでは、何でもかんでもMVCという考えに沿ってモデルを作っていました。
添付資料を読んでいきます！

2018-03-09 09:16 UTC, takeyuweb commented
@shiraryu MVCはMVCなんですがM=ActiveRecordじゃないぞってところですね。多くの場合はそれでよいのですが、最初に作ったFeedはActiveRecordである必要がないので。

ちなみに `RSS::Parser.parse(url)` みたいに一発じゃなくて、ダウンロード、解析というロジックが必要になるとみていたので、それをモジュールにまとめてコントローラーから切り出して貰おうかな、と、はじめ思っていました。

2018-03-09 09:32 UTC, shiraryu commented
@takeyuweb 
M=ActiveRecordじゃないというところが肝ですね、、、
僕は完全に思い込んでました（汗）

moduleも使用した覚えがなく、理解不足ではありますが。。。

2018-03-09 11:17 UTC, shiraryu commented on app/models/feed.rb
> +Feed = Class.new(ApplicationRecord)
@takeyuweb 
やや、「# RSSから記事リストを取得して返す」という関数のところの意味が違うのかもしれないですが、一旦修正し、再度pushしたコードを見ていただきたいです。
よろしくお願いいたします。

2018-03-09 13:54 UTC, itkrt2y commented on app/models/feed.rb
> +    url = Feed.first.url
selfメソッド内部なら、同じくApplicationRecordのおかげでselfメソッドとして定義されてる `first` はクラス指定なしでも呼べると思う

```rb
url = first.url
```

2018-03-09 13:54 UTC, itkrt2y commented on app/models/feed.rb
> +    url = Feed.first.url
ここまで来たら、変数に入れるほどの長さでもなくなる

2018-03-09 13:56 UTC, itkrt2y commented on app/views/feeds/new.html.erb
> +  <%= f.label :登録フォーム %><br />
日本語でのSymbol、初めて見た気がする。別に動くけど理由がないならこの場合はStringで定義するのが一般的ですね。どうせ内部でStringに変換されるだろうから二度手間だし

2018-03-09 13:58 UTC, itkrt2y commented on db/migrate/20180309033241_create_feeds.rb
> +      t.string :url
@takeyuweb なんで `default: ''` にするんです？

2018-03-09 14:01 UTC, itkrt2y commented on app/controllers/feeds_controller.rb
> +    @feed = Feed.channel
俺なら `@channel = Feed.channel` にする。channelをfeedという名前で持つのは紛らわしいのでよろしくないので

2018-03-09 14:02 UTC, itkrt2y commented on app/views/feeds/new.html.erb
> +  <%= f.label :登録フォーム %><br />
あと、せっかくならばlabelをクリックしたらtext_fieldにフォーカスされるようにしたい

2018-03-09 14:38 UTC, shiraryu commented on app/models/feed.rb
> +    url = Feed.first.url
呼べました（涙）ありがとうございます！
そのまま（）内に入れて使います！

2018-03-09 14:38 UTC, shiraryu commented on app/views/feeds/new.html.erb
> +  <%= f.label :登録フォーム %><br />
変なものをお見せしました（汗）承知しました。
labelクリックやってみます！

2018-03-09 14:40 UTC, shiraryu commented on app/controllers/feeds_controller.rb
> +    @feed = Feed.channel
本当ですね、、、完全にわかりやすいです（汗）
わかりやすく作ることをもっと考えるようにします！

2018-03-09 14:43 UTC, itkrt2y commented on app/views/feeds/new.html.erb
> +      <div id = "error_explanation">
すごい細かい指摘になりますが、HTMLでは属性定義にスペース入れないのが一般的です

```html
<div id="error_explanation">
```

2018-03-09 14:45 UTC, itkrt2y commented on app/views/feeds/new.html.erb
> +  <% if @feed.errors.any? %>
どうでもレベルかもしれませんが、エラー表示の定義は `form_for` の外に書いた方が個人的には見やすい

2018-03-09 15:03 UTC, shiraryu commented on app/views/feeds/new.html.erb
> +      <div id = "error_explanation">
いえ、ありがたいです！知りもしませんでした。。。
気をつけます！

2018-03-09 15:04 UTC, shiraryu commented on app/views/feeds/new.html.erb
> +  <% if @feed.errors.any? %>
今、修正したのですが、、、
外の方が断然見やすいし、わかりやすいです（涙）

2018-03-09 15:35 UTC, itkrt2y commented on app/views/feeds/new.html.erb
> +<%= form_for(@feed) do |f| %>
そういえば、Rails5.1以降を使っているということは、一応Rails的には `form_for` よりも `form_with` を使うのが推奨されているはず。まだRails5.1をみんなが使えているとは言い難い時代なので、ググっても「もしかして： form_for」とか言われちゃう不遇の機能ですが。

今回は `form_for` でいいですが、未来に向けて `form_with` での書き方を示しておくと、多分以下になる（何も見ずに書いたから間違えてるかも）

```rb
<%= form_with(model: @feed, local: false) do |f| %>
```

2018-03-09 17:36 UTC, shiraryu commented on app/views/feeds/new.html.erb
> +<%= form_for(@feed) do |f| %>
form_with推奨も全く知りませんでした。。。
未来に向けて使い方などを頭に入れておきます！

「もしかして： form_for」

で、、、出ました、、、
書き方、あってます（すごい）

2018-03-10 08:35 UTC, shiraryu commented
p、、、pushし忘れていました（汗）

2018-03-12 01:16 UTC, shiraryu commented
見にくいかもですが、一旦、一つのRSS登録&表示に関するコード記述をコメントアウトし、複数表示するコードを記述してみました。空いてる際に見ていただきたいです。よろしくお願いいたします。

2018-03-12 06:31 UTC, itkrt2y commented
複数表示、いいですね 👍 

いらなくなったコードは消しちゃっていいですよ。もし前の状態に戻したくなったならば、gitで巻き戻せばいいだけですし。

2018-03-12 06:33 UTC, itkrt2y commented on app/models/feed.rb
> +    end
これがダメってわけじゃなくて好みの話ですが、僕ならこれくらいの複雑度ならばワンライナーにしてしまう

```rb
all.map{ |feed| RSS::Parser.parse(feed.url).channel }
```

2018-03-12 06:38 UTC, itkrt2y commented on app/models/feed.rb
> +  validates :url, presence: true
せっかくならば、値がURL形式になっているかどうかを判別するのもいいかも。
`URI::regexp` との比較でできると思う https://docs.ruby-lang.org/ja/latest/method/URI/s/regexp.html

2018-03-12 06:41 UTC, shiraryu commented on app/models/feed.rb
> +    end
@itkrt2y  ご確認ありがとうございます。いらなくなったコード、消しておきます！
１行で収まってるのを見ると、、、断然スッキリしてます（汗）
こちらの書き方に修正します！(今、cherry本で{ }の書き方を学んでいる最中なのに、自発的に適用できなかった自分に無念す、、、)

2018-03-12 06:46 UTC, shiraryu commented on app/models/feed.rb
> +  validates :url, presence: true
調べて記述してみます！

2018-03-12 07:57 UTC, shiraryu commented
不必要なコード削除、コード修正、バリデーション追加を行いました。
ご確認をよろしくお願い致します。

2018-03-12 09:34 UTC, takeyuweb commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
いい機会なので、このバリデーションが正しいことのテストを書いてみましょうか。

`Feed` クラスのテストで、

- `url` にHTTPまたはHTTPSのURLを渡すと通る
- `url` にURL以外を渡すと `url` のエラーを検出する

バリデーションに失敗したとき、それが何のエラーかは `feed.errors[]` を使うとわかります。

https://railsguides.jp/active_record_validations.html#errors

試してないけどたぶんこんな感じ

```ruby
feed = Feed.new(url: 'hogehoge')
feed.valid? #=> false
feed.errors[:url] #=> ['の入力値が不正です']
```

このことを使って、テストが書けると思います。
（スクールでテスト書くレッスンありました？）

2018-03-12 09:34 UTC, takeyuweb requested changes

2018-03-12 09:34 UTC, takeyuweb commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
いい機会なので、このバリデーションが正しいことのテストを書いてみましょうか。

`Feed` クラスのテストで、

- `url` にHTTPまたはHTTPSのURLを渡すと通る
- `url` にURL以外を渡すと `url` のエラーを検出する

バリデーションに失敗したとき、それが何のエラーかは `feed.errors[]` を使うとわかります。

https://railsguides.jp/active_record_validations.html#errors

試してないけどたぶんこんな感じ

```ruby
feed = Feed.new(url: 'hogehoge')
feed.valid? #=> false
feed.errors[:url] #=> ['の入力値が不正です']
```

このことを使って、テストが書けると思います。
（スクールでテスト書くレッスンありました？）

2018-03-12 09:40 UTC, takeyuweb commented on app/views/feeds/new.html.erb
> +<%= form_for(@feed) do |f| %>
これまでは、場面によって `form_for` と `form_tag` それぞれの使いどころを知って使い分ける必要があったんですが、どっちにも使える `form_with` が登場したんですよね。

https://railsguides.jp/5_1_release_notes.html#form-for%E3%81%A8form-tag%E3%81%AEform-with%E3%81%B8%E3%81%AE%E7%B5%B1%E5%90%88

2018-03-12 11:32 UTC, shiraryu commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
取り掛かってみます！スクールではテストの書き方をほとんど教わっていません（汗）
テストとはこんなものですよー、、、って感じで、ほんの少し触れたぐらいでした（涙）

2018-03-12 11:53 UTC, takeyuweb commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
まぁテストがなくてつらい目にあわないとありがたみは伝わりづらいかもしれませんね。

チェリー本だと3章がテストについての説明です。
RSpecでもいいですが、まずは標準であるもので慣れてほしいので、チェリー本3章とRailsガイドを参考にMinitestで書いてみてください。

Railsガイド
https://railsguides.jp/testing.html
今回は『モデルに対する単体テスト』に該当すると思います。

以下の内容で `test/models/feeds_test.rb` を作成して、そこからテストに挑戦してみてください。


```ruby
require 'test_helper'
 
class FeedTest < ActiveSupport::TestCase

end
```

2018-03-12 13:07 UTC, shiraryu commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
承知しました、取り組んでいきます！

2018-03-13 03:32 UTC, shiraryu commented
test、ややこれじゃない感があるのですが、一旦ご確認いただき、
レビュー（ご教授）いただきたいです。よろしくお願いいたします。

2018-03-13 03:58 UTC, takeyuweb requested changes
あと、インデント

```ruby
@feed_true ||= Feed.new(
url: "https://rss-weather.yahoo.co.jp/rss/days/7320.xml"
)
```

のところ、やるなら

```ruby
@feed_true ||= Feed.new(
  url: "https://rss-weather.yahoo.co.jp/rss/days/7320.xml"
)
```
のようにインデントを入れます。

もっとも、この場合はそもそも改行いらなくない？感のほうが強いですが。

2018-03-13 03:58 UTC, takeyuweb commented on test/models/feed_test.rb
> +    assert feed_true.valid?
`feed_true` メソッドに切り出したのはなぜです？

2018-03-13 03:58 UTC, takeyuweb commented on test/models/feed_test.rb
> +    assert feed_true.valid?
それはそれとして、

```ruby
@feed_true ||= Feed.new(url: "https://rss-weather.yahoo.co.jp/rss/days/7320.xml")
```

このような手法をメモ化（Memoize）といいます。が、ここでは必要ありません。
たぶんよくわかっておらず、そういうコードを見たから真似してみたのだと思います。Railsのコントローラーなんかでよくやりますよね。

そういうコードではなぜこうやっていたのか？何が起きているのか、そしてここではなぜ不要なのか？まずはメモ化について調べたうえで考えてみてください。

2018-03-13 03:58 UTC, takeyuweb commented on test/models/feed_test.rb
> +    assert feed_false.invalid?
これ @shiraryu さんが期待するテストができていないと思います。

`feed_false` の戻り値は `Feed.new(url: "")` になっていますよね？ということは…？

2018-03-13 04:15 UTC, itkrt2y commented on test/models/feed_test.rb
> +    url: "https://rss-weather.yahoo.co.jp/rss/days/7320.xml"
インデント、もう一つ下げてほしい（もしくは改行しないか）

2018-03-13 05:07 UTC, shiraryu commented on test/models/feed_test.rb
> +    assert feed_true.valid?
はい、、、なかなかMinitestの記述がつかめず、書いた次第です（汗）
メモ化を調べ、再度考えてみます！

2018-03-13 05:09 UTC, shiraryu commented on test/models/feed_test.rb
> +    assert feed_false.invalid?
はっ！なっていませんね。。。この部分も含め、全体的に考え直します！

2018-03-13 05:10 UTC, shiraryu commented
インデント（or  改行しない）などを含め、メモ化などから調べつつ再度考えていきます（汗）

2018-03-13 05:28 UTC, takeyuweb commented
あ、あと

> test修正（SideCL） 

SideCL じゃなくて SideCI です。シー・エルではなくシー・アイ :stuck_out_tongue:

2018-03-13 05:33 UTC, shiraryu commented
はっ！！！！完全にCLだと思っていました:sweat_drops:

2018-03-13 06:46 UTC, shiraryu commented
テストコードを修正してみました。再度ご確認をよろしくお願い致します（汗）

2018-03-13 07:50 UTC, itkrt2y commented on test/models/feed_test.rb
> +  end
話すと長くなる話題なので掻い摘みますが、テストには「1つのテストで実行するassertは1回にする」という考え方があります。今回でいうと `test do ~ end` の中のassertは1回にする、という話。

この理由は、以下のようにいろいろあります

- assert1回で済まないのはメソッドが責務を複数持っている（責務が適切に分離されていない）から
- テストを実行した時に出力されるメッセージをわかりやすくしたいから
- あるひとつのassertが落ちたら、そのあとのassertが実行されないから
- etc

現実的には、Modelのメソッドでもなければ一回実行した結果複数assertしたいことはあるもので、絶対の原則ではないのですが。
例えば、controllerテストだと、1回のリクエストに対してレスポンスステータスとレスポンスボディの両方をassertしたいってことはありますし。

で、何が言いたいかというと、今回のこのテストは流石に一つにまとめすぎかなということ。
こういう内容では、assertは別のテストに作って適切な名前付けをしてあげる方がよいです。

例えばこんな感じかな。大体これのパクリだけど https://railsguides.jp/testing.html#%E3%83%86%E3%82%B9%E3%83%88%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B

```rb
test "should save feed with valid url" do
  feed = Feed.new(url: "https://rss-weather.yahoo.co.jp/rss/days/7320.xml")
  assert feed.save
end

test "should not save feed when scheme is not http/https" do
  feed = Feed.new(url: "javascript://rss-weather.yahoo.co.jp/rss/days/7320.xml")
  assert_not feed.save
end

test "should not save feed without url" do
  feed = Feed.new(url: "")
  assert_not feed.save
end
```

2018-03-13 07:51 UTC, itkrt2y commented on test/models/feed_test.rb
> +    assert_not feed_blank.save
これだけ `valid?` `invalid?` じゃなくて `save` にしたの、なんででしょう？

2018-03-13 08:06 UTC, shiraryu commented on test/models/feed_test.rb
> +  end
詳細な説明、ありがとうございます！
勝手ながら「まとめた方が良いのかな、、、」と、安易な気持ちでまとめていました。
別々に分けるよう修正していきます！

2018-03-13 08:14 UTC, shiraryu commented on test/models/feed_test.rb
> +    assert_not feed_blank.save
あまり明確な目的はなく、
https://railsguides.jp/testing.html#%E3%83%86%E3%82%B9%E3%83%88%E3%82%92%E5%AE%9F%E8%A1%8C%E3%81%99%E3%82%8B
こちらの記事を参考に書いていたのですが、、、invalid?でよかったですね（汗）
統一するところ、注意していきます。

2018-03-13 08:57 UTC, shiraryu commented
ひとまとまりのテストコードを分けました。ご確認をよろしくお願いいたします！
（板倉さんのテスト名をそのまま、、、すいません（汗））

2018-03-13 09:04 UTC, itkrt2y commented on test/models/feed_test.rb
> +  end
テスト、いいですね 👍

2018-03-13 09:05 UTC, itkrt2y commented on test/models/feed_test.rb
> +    feed_false = Feed.new(url: "javascript:alert('XSS');//http://shiraishi.jp/")
falseとかblankってpostfixいらない

2018-03-13 09:06 UTC, itkrt2y commented on test/models/feed_test.rb
> +    feed_false = Feed.new(url: "javascript:alert('XSS');//http://shiraishi.jp/")
変数名とかメソッド名の名付けの理想は「中身を見なくても、名前でそれが何かを正しく言い表していること」になります

2018-03-13 09:07 UTC, shiraryu commented on test/models/feed_test.rb
> +    feed_false = Feed.new(url: "javascript:alert('XSS');//http://shiraishi.jp/")
無駄が多くてすいません（汗）
修正しました！

2018-03-13 09:10 UTC, itkrt2y commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
試してみないと自信ないですが、これって空文字渡すとformatとpresenceの両方に引っかかって、エラーメッセージ２つでないですかね？

2018-03-13 09:11 UTC, itkrt2y commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
そうだったら鬱陶しいので、 `presence: true` とっちゃっていいのですが

2018-03-13 09:14 UTC, shiraryu commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
２つでます。。。これはよくないですね（汗）

2018-03-13 09:22 UTC, shiraryu commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
presence: trueを削除修正＆動作確認行いました！

2018-03-13 09:31 UTC, takeyuweb commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
あるいは

`validates :url, format: { with: /\A#{URI::regexp(%w(http https))}\z/, allow_blank:true }, presence: true`

で、

- 必須入力
- 入力されている場合は書式チェック

になったように思いますがどうでしょう？

2018-03-13 09:32 UTC, takeyuweb commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
重箱の隅をつつくようですみませんが、気になったもので…

2018-03-13 09:36 UTC, itkrt2y commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
それはまあどういうエラーを出したいかによる。今はそこまでこだわった実装にする必要はないかな

2018-03-13 09:36 UTC, itkrt2y commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
俺のコメントがすでにこだわりすぎかもですが

2018-03-13 09:47 UTC, itkrt2y commented
よさげ

2018-03-13 10:18 UTC, takeyuweb approved these changes

2018-03-13 10:18 UTC, merged

2018-03-13 13:11 UTC, shiraryu commented on app/models/feed.rb
> +  validates :url, format: /\A#{URI::regexp(%w(http https))}\z/, presence: true
な、、なるほどです。。。そのように書くと、
・必須入力
・入力されている場合は書式チェック
というバリーデーションになりました（確認してみました）
ありがとうございます！（メモメモ）

こだわり感謝です！！