fix_require
takeyuwebinc/sample-feedreader-rails pull request #8
Opened 2018-03-06 04:33 UTC by shiraryu

refs #1 

・require位置修正
・feed.rb、migration削除

ご確認をよろしくお願いいたします。

![2018-03-06 13 31 53](https://user-images.githubusercontent.com/26644768/37014276-de2168cc-2142-11e8-850f-f412de37d6d3.png)

2018-03-06 06:33 UTC, takeyuweb commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2018_03_05_123229) do
これ、migrationを削除したならこれも変わってくると思うのでこれも削除かな
あとデータベースは作り直したほうがよいかと。 feedsテーブルが残ってると思う

2018-03-06 06:35 UTC, takeyuweb requested changes
あと、このPRに対して、SideCIというツールが指摘している内容も対応してみてください。

ある程度自分で判断ができるようになればこういうツールは対応するしないを判断したり、部分的に無効にしたりするのですが、今の段階では指摘とその理由を考えるのも訓練になると思うので。

2018-03-06 06:35 UTC, takeyuweb commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2018_03_05_123229) do
これ、migrationを削除したならこれも変わってくると思うのでこれも削除かな
あとデータベースは作り直したほうがよいかと。 feedsテーブルが残ってると思う

2018-03-06 06:39 UTC, takeyuweb commented
@shiraryu おっとー
コミットごとにPR作らなくていいですよー
修正をpushするとprも更新されていくので、今回であれば issue#1 に対してpushしてもらえればOKです

2018-03-06 06:44 UTC, shiraryu commented
@takeyuweb 
 issue#1 に対してpushする、承知しました！

2018-03-06 06:45 UTC, shiraryu commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2018_03_05_123229) do
データベース作り直します＆SideCl確認していきます！
SideClって何だろう、、、と思っていました（汗）

2018-03-06 06:56 UTC, itkrt2y commented
細かい指摘にはなりますが、用語の使い方が気になったので指摘しておくと、pushとPRは違います。
pushはgitがremote repositoryにlocal repositoryの変更を反映することで、PRはGitHubの機能で、あるbranchに別のbranchをmerge/rebaseしてくれるよう依頼することです。

GitHubのことをgitって言っちゃうのと同じ間違い

2018-03-06 07:12 UTC, shiraryu commented
@itkrt2y 　いえ、、、pushやPRの部分は理解が結構ゴチャゴチャになっています（汗）
スクールでのチーム開発では、一つの作業に対し『PR→レビュー→新しくブランチ切る→修正→新しくPR』となっていまして、毎度毎度PRを作っていました。。。
つまり、一つの作業に対し、PR→レビュー→同じブランチで修正→初回のPRにPush
という感じの流れであっていますでしょうか？（板倉さんアドバイスを含むと）

2018-03-06 07:28 UTC, itkrt2y commented
>一つの作業に対し、PR→レビュー→同じブランチで修正→初回のPRにPush
>という感じの流れであっていますでしょうか？

まあそういう感じです。

ここら辺の役割が理解できてないのは、gitのbranchをまだ正しく理解できてないからかな。
PRはbranch単位でたてられるものなので、gitのbranchの役割がわかればGitHubのPRの役割もわかるはず。

gitのbranchはいれようとしている変更ごとに作られるもので、例えば今回で言えば「RSS一覧画面作成」という目的に対してbranchが作られていて（作られているべきで）、それを実際にmaster branchにマージしていいかのお伺いを立てる場がこのGitHubのPRという機能。

なので、まずはgitのbranchを理解して、branchに正しく名前をつけるところから始めるといいかも（issue#1みたいな名前は場合によってはOKだけど、あまり好ましくはない）

2018-03-06 07:45 UTC, shiraryu commented
@itkrt2y そうですね、、、branchへの理解が足らず、目的に対してポンポンとブランチを作成していました。現在はissue#1-4ブランチを作成し、pushしてしまっているため、このままこのブランチを使うようにします。。。が、次の機能作成からbranchを理解しつつ進めていきます。（名前も正しく、目的に沿ってつける）丁寧なご説明ありがとうございます！

2018-03-06 07:47 UTC, itkrt2y commented
他のbranchにコミットを混ぜたいなら、cherry pickとかrebaseとか、あとは一つのPRの中でやるとログが汚くなりそうですけどmergeするとかありますよ

2018-03-06 07:52 UTC, shiraryu commented
@itkrt2y やり方確認してみます！

2018-03-06 12:06 UTC, shiraryu commented
と、、、とりあえずですが先に修正をコミットしました。
・schema削除
・DB作り直し
ご確認をよろしくお願いいたします。
これからrebaseなどのやり方を確認していきます！

2018-03-06 15:01 UTC, itkrt2y commented
コミットメッセージを `_` で繋いでるの気になる。
ブランチ名は1つなぎの単語にしなきゃいけないですけど、コミットメッセージはそういうの不要のただの文章です。
あと、コミットメッセージは英語面倒だったら日本語でもいいです。今頑張るべきところはそこじゃないと思うので

2018-03-06 15:06 UTC, itkrt2y commented on app/views/feeds/index.html.erb
> +  <p><%= item.pubDate.strftime('%Y年%m月%d日 %H:%M') %></p>
`p` タグってparagraph、つまり段落のことなので、 `p`  で囲むならこの3つセットで囲む方が意味的には（横文字で言うと、セマンティクス的には）正しいです。
改行は `div` で囲うか各行 `br` するか悩むところですけど、まあどっちでもいい

2018-03-06 15:09 UTC, itkrt2y commented on app/views/feeds/index.html.erb
> +  <p><%= item.pubDate.strftime('%Y年%m月%d日 %H:%M') %></p>
んで、段落ごとの空白の取り方は `br` （改行）を使うのではなく、 `p` に対して `margin` を当てるのが正しい。（ `p` タグ全てにスタイルを当てるのは流石に盈虚範囲がでかすぎるので、classを定義してそれに対してスタイルを当てるべき）

2018-03-06 17:36 UTC, shiraryu commented on app/views/feeds/index.html.erb
> +  <p><%= item.pubDate.strftime('%Y年%m月%d日 %H:%M') %></p>
pタグも含めて一つ一つに意味があるということを考慮せずに記述していました。
brもこれまでは、cssとの役割を明確に分けずに無作為に多用し、、、（汗）
ありがとうございます、修正してきます！（朝）

2018-03-06 17:36 UTC, shiraryu commented
@itkrt2y　夜遅くにありがとうございます！
ここ（コミットメッセージ部分）もまた、branchに対する理解不足です（汗）
はい、今ここは英語ではなく（英語苦手です）日本語で書くようにします！

2018-03-07 02:15 UTC, takeyuweb approved these changes

2018-03-07 02:27 UTC, takeyuweb requested changes
SideCIについて説明が必要でしたね。
かいつまんで言うと、SideCIはPull-Requestに対して、ソースコード上のよくない傾向を見つけて指摘してくれるコードレビューの自動化（支援）ツールです。

指摘は、読みづらかったり保守しづらくなる傾向にあるとされているコードの書き方についてのベストプラクティスなどをもとに機械的に行われます。

利用者は個々の指摘に対して修正して再度Pushするか、修正が不要であると判断できるときは理由をコメントしつつクローズ（この指摘はあてはまらない、あるいは対応の必要がないとして無視する）かのどちらかの対応をします。

今回でいうと、
https://sideci.com/gh/123871775/pull_requests/8
Remove empty helpers というベストプラクティスに従うように指摘があった、ということです。

これに対して @shiraryu さんは、修正するか、クローズかのどちらかの対応が求められました。

今回、たぶん使い方がよくわからなくてクローズされたのだと思いますが、基本的には修正するようにしてください。

というわけで、クローズした指摘をリオープンして、修正してみていただけますか？

2018-03-07 02:29 UTC, takeyuweb commented
SideCIに限らず、わからないことはまずググって調べて、それでもわからなければ聞いてくださいー
調べた結果「こういうこと？」という確認でもいいのでお気軽にどうぞ

2018-03-07 02:33 UTC, shiraryu commented
@takeyuweb 
ご説明ありがとうございます。承知しました、まず調べてから取り組む癖をつけていきます。
修正してみます！

2018-03-07 02:41 UTC, itkrt2y commented
暇があるときにRuby Style Guide読んでおいてください。これは100%従わなければならないものではないですが、一番ベーシックなRubyのコーディング規約なので。
https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md

2018-03-07 02:45 UTC, shiraryu commented
@itkrt2y ありがとうございます！指針がわからずに書いているという問題を感じていました。。。
読んでいきます！

2018-03-07 02:55 UTC, takeyuweb commented
@shiraryu SideCIのステータスがfixedになって✔が付いたのがわかったでしょうか？

慣れてくると指摘が邪魔に感じたり、本質的でない指摘が気になったりして、たとえばコーディングスタイルに関する指摘を無効にしたりと設定（俗に『調教』といいます）するのですが、コーディングスタイルの基本が身についてくるまではひとまず従っておくとよいと思います。ただし、なぜか？もセットで。それがないと後々必要不要の判断ができない人になるので。

2018-03-07 02:55 UTC, takeyuweb approved these changes

2018-03-07 02:56 UTC, merged

2018-03-07 03:04 UTC, shiraryu commented
@takeyuweb はい！fixedになるところを確認できました。
必要不要の判断ができない人になるのは辛いので、従いつつ基本を身につけられるよう取んでいきます！